<h1>Campaign</h1>
The campaign takes place on Grabin, in and around the city of Sangreal. 

<h2>Sangreal: City of Merchants. The Sky Island</h2>
Sangreal is a city of merchants and is located on an ancient roadway up against the Great Desert. Everything has a price here, and the government is that of a confederation of merchant lords. The city itself is a highly defensible plateau surrounded by nothing but boulder fields. The plateau is high enough to allow for clouds to be mined for much of the drinking water used by the sparse population. While this is called a city it is more of a close collection of fortified towns, each with a different merchant lord. The size of the plateau, being over 20 miles in length and 5 miles at its widest point makes full population rather spread out. The small agricultural plots atop the plateau are mostly made of soil created by the citizens themselves. Houses are cut into the rock of the plateau. The "center" of Sangeal, and indeed what most outsiders think of when they hear the name, is the central bazaar, which is housed on rock spur off of the main plateau, only reachable by the sky bridge. While the access is relatively narrow the bazaar itself is immense covering over two square kilometers and extending down into the lower shops cut into the stone below. The crest of Sangreal is white field with a gold tower.

Extremely religious, sangrealians all have a religion and have very strong feelings about it. They generally dismiss academic learning unless it informs either religious or business dealings. The culture has a very average attitude towards both martial prowess and nature. Things must be respected, but not at expense of what is important.

Sangraleian society is not very egalitarian, and has almost no social mobility. Property is paramount and theft is nearly as serious a crime as murder. Slavery is quite common in this culture, and life has very little value. Marriage is Polyandrous, with each woman married to as many men as she can afford. Outsiders would view this more as a business merger. Wives can divorce their husbands, but are required to give them enough to survive. Property and inheritance is through the maternal (mother's) line, with everything going to the oldest daughter. This system is a bit "movable" through ghost marriage if the matron decides to disinherit her eldest.

<h2>The Great Houses</h2>
The city is ruled by a council of the 13 most powerful, read: wealthiest families in the city. This sometimes changes, but not very often. Most economic activity in the city are either directly from these families or from a large group of associated families and groups that form what are effectively "vassals" of these power bases. Colloqually, these vassels all together are called The Market. 